2016/11/19 11:13:57 [error] 1078#1078: *29 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/case/config/module_user.php): failed to open stream: No such file or directory in /var/www/case/config/web.php on line 52
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/case/config/module_user.php' (include_path='.:/usr/share/php') in /var/www/case/config/web.php on line 52" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/11/19 11:15:30 [error] 1078#1078: *31 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/case/config/module_user.php): failed to open stream: No such file or directory in /var/www/case/config/web.php on line 52
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/case/config/module_user.php' (include_path='.:/usr/share/php') in /var/www/case/config/web.php on line 52" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/11/28 18:11:05 [error] 1056#1056: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /template/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/11/28 18:12:11 [error] 1056#1056: *8 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /template/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/11/28 18:12:12 [error] 1056#1056: *8 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /template/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/11/28 18:13:34 [error] 1056#1056: *11 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /t2/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/11/29 12:33:16 [error] 1100#1100: *28 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Method yii\bootstrap\ActiveField::__toString() must not throw an exception, caught Error: Class 'app\models\ArrayHelper' not found in /var/www/case/modules/cases/views/admin/_case.php on line 0" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /admin/cases/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local", referrer: "http://case.local/admin/cases/index"
2016/12/01 13:33:22 [error] 1026#1026: *804 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
ReflectionException: Method yii\widgets\BaseListView::yii\widgets\{closure}() does not exist in /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php:199
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(199): ReflectionMethod->__construct('yii\\widgets\\Bas...', 'yii\\widgets\\{cl...')
#1 /var/www/case/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('yii\\widgets\\Bas...')
#2 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(249): require('/var/www/case/v...')
#3 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#4 /var/www/case/vendor/yiisoft/yii2/views/errorHandler/exception.php(385): yii\web\ErrorHandler->renderCallStackItem(NULL, NULL, 'yii\\widgets\\Bas...', 'yii\\widgets\\{cl...', Array, 15)
#5 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(249): require('/var/www/case/v...')
#6 /var/" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /admin/operations/index HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local", referrer: "http://case.local/admin/operations/create"
2016/12/01 18:05:36 [error] 1028#1028: *1158 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
ReflectionException: Method yii\base\View::{closure}() does not exist in /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php:199
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(199): ReflectionMethod->__construct('yii\\base\\View', '{closure}')
#1 /var/www/case/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('yii\\base\\View::...')
#2 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(249): require('/var/www/case/v...')
#3 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#4 /var/www/case/vendor/yiisoft/yii2/views/errorHandler/exception.php(385): yii\web\ErrorHandler->renderCallStackItem(NULL, NULL, 'yii\\base\\View', '{closure}', Array, 3)
#5 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(249): require('/var/www/case/v...')
#6 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(113):" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /admin/operations/view?id=6 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local", referrer: "http://case.local/admin/operations/create"
2016/12/05 12:18:43 [error] 963#963: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'case'@'localhost' (using password: YES) in /var/www/case/vendor/yiisoft/yii2/db/Connection.php:602
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(602): PDO->__construct('mysql:host=loca...', 'case', 'z1Ec3U2udjihvms...', NULL)
#1 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(544): yii\db\Connection->createPdoInstance()
#2 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(863): yii\db\Connection->open()
#3 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(850): yii\db\Connection->getMasterPdo()
#4 /var/www/case/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#5 /var/www/case/vendor/yiisoft/yii2/db/Command.php(894): yii\db\Command->prepare(true)
#6 /var/www/case/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#7 /var/www/case/vendor/yiisoft/yii2/db/mysql/Schema.php(199): yii\db\Command->quer" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /balance HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/05 12:20:56 [error] 964#964: *28 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1044] Access denied for user 'case'@'localhost' to database 'case' in /var/www/case/vendor/yiisoft/yii2/db/Connection.php:602
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(602): PDO->__construct('mysql:host=loca...', 'case', 'z1Ec3U2udjihvms...', NULL)
#1 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(544): yii\db\Connection->createPdoInstance()
#2 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(863): yii\db\Connection->open()
#3 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(850): yii\db\Connection->getMasterPdo()
#4 /var/www/case/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#5 /var/www/case/vendor/yiisoft/yii2/db/Command.php(894): yii\db\Command->prepare(true)
#6 /var/www/case/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#7 /var/www/case/vendor/yiisoft/yii2/db/mysql/Schema.php(199): yii\db\Command->queryAl" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /balance HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/05 12:20:57 [error] 964#964: *28 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1044] Access denied for user 'case'@'localhost' to database 'case' in /var/www/case/vendor/yiisoft/yii2/db/Connection.php:602
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(602): PDO->__construct('mysql:host=loca...', 'case', 'z1Ec3U2udjihvms...', NULL)
#1 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(544): yii\db\Connection->createPdoInstance()
#2 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(863): yii\db\Connection->open()
#3 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(850): yii\db\Connection->getMasterPdo()
#4 /var/www/case/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#5 /var/www/case/vendor/yiisoft/yii2/db/Command.php(894): yii\db\Command->prepare(true)
#6 /var/www/case/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#7 /var/www/case/vendor/yiisoft/yii2/db/mysql/Schema.php(199): yii\db\Command->queryAl" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /balance HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/05 12:20:57 [error] 964#964: *28 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1044] Access denied for user 'case'@'localhost' to database 'case' in /var/www/case/vendor/yiisoft/yii2/db/Connection.php:602
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(602): PDO->__construct('mysql:host=loca...', 'case', 'z1Ec3U2udjihvms...', NULL)
#1 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(544): yii\db\Connection->createPdoInstance()
#2 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(863): yii\db\Connection->open()
#3 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(850): yii\db\Connection->getMasterPdo()
#4 /var/www/case/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#5 /var/www/case/vendor/yiisoft/yii2/db/Command.php(894): yii\db\Command->prepare(true)
#6 /var/www/case/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#7 /var/www/case/vendor/yiisoft/yii2/db/mysql/Schema.php(199): yii\db\Command->queryAl" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /balance HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/05 12:20:57 [error] 964#964: *28 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1044] Access denied for user 'case'@'localhost' to database 'case' in /var/www/case/vendor/yiisoft/yii2/db/Connection.php:602
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(602): PDO->__construct('mysql:host=loca...', 'case', 'z1Ec3U2udjihvms...', NULL)
#1 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(544): yii\db\Connection->createPdoInstance()
#2 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(863): yii\db\Connection->open()
#3 /var/www/case/vendor/yiisoft/yii2/db/Connection.php(850): yii\db\Connection->getMasterPdo()
#4 /var/www/case/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#5 /var/www/case/vendor/yiisoft/yii2/db/Command.php(894): yii\db\Command->prepare(true)
#6 /var/www/case/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#7 /var/www/case/vendor/yiisoft/yii2/db/mysql/Schema.php(199): yii\db\Command->queryAl" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /balance HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/05 13:36:08 [error] 964#964: *115 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'yarcode\freekassa\Merchant' not found in /var/www/case/config/web.php:61
Stack trace:
#0 /var/www/case/web/index.php(10): require()
#1 {main}
  thrown in /var/www/case/config/web.php on line 61" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/06 18:01:53 [error] 979#979: *134 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
ReflectionException: Method GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() does not exist in /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php:199
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(199): ReflectionMethod->__construct('GuzzleHttp\\Hand...', 'GuzzleHttp\\Hand...')
#1 /var/www/case/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('GuzzleHttp\\Hand...')
#2 /var/www/case/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/case/v...')
#3 /var/www/case/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/case/v...', Array)
#4 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('/var/www/case/v...', Array, Object(yii\web\ErrorHandler))
#5 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 /var/www/case/vendor/yiisof" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /operations/index/cashout HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/06 18:02:45 [error] 979#979: *134 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
ReflectionException: Method GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() does not exist in /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php:199
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(199): ReflectionMethod->__construct('GuzzleHttp\\Hand...', 'GuzzleHttp\\Hand...')
#1 /var/www/case/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('GuzzleHttp\\Hand...')
#2 /var/www/case/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/case/v...')
#3 /var/www/case/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/case/v...', Array)
#4 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('/var/www/case/v...', Array, Object(yii\web\ErrorHandler))
#5 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 /var/www/case/vendor/yiisof" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /operations/index/cashout HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/06 18:02:46 [error] 979#979: *134 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
ReflectionException: Method GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() does not exist in /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php:199
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(199): ReflectionMethod->__construct('GuzzleHttp\\Hand...', 'GuzzleHttp\\Hand...')
#1 /var/www/case/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('GuzzleHttp\\Hand...')
#2 /var/www/case/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/case/v...')
#3 /var/www/case/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/case/v...', Array)
#4 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('/var/www/case/v...', Array, Object(yii\web\ErrorHandler))
#5 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 /var/www/case/vendor/yiisof" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /operations/index/cashout HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/12 17:27:13 [error] 1012#1012: *257 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'AccessControl' not found in /var/www/case/config/web.php:87
Stack trace:
#0 /var/www/case/web/index.php(10): require()
#1 {main}
  thrown in /var/www/case/config/web.php on line 87" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /settings/manager/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/12 17:27:26 [error] 1012#1012: *257 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function AccessControl() in /var/www/case/config/web.php:87
Stack trace:
#0 /var/www/case/web/index.php(10): require()
#1 {main}
  thrown in /var/www/case/config/web.php on line 87" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /settings/manager/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/12 17:30:20 [error] 1012#1012: *277 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'AccessControl' not found in /var/www/case/config/web.php:88
Stack trace:
#0 /var/www/case/web/index.php(10): require()
#1 {main}
  thrown in /var/www/case/config/web.php on line 88" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /settings/manager/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/12 17:30:44 [error] 1012#1012: *277 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'AccessRule' not found in /var/www/case/config/web.php:90
Stack trace:
#0 /var/www/case/web/index.php(10): require()
#1 {main}
  thrown in /var/www/case/config/web.php on line 90" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /settings/manager/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
2016/12/12 17:34:36 [error] 1012#1012: *331 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected end of file, expecting ';' in /var/www/case/config/access.php on line 16" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /settings/manager/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local", referrer: "http://case.local/user/login"
2016/12/13 19:16:29 [error] 966#966: *98 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class app\models\RegistrationForm because the name is already in use in /var/www/case/models/RegistrationForm.php on line 7" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /user/register HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local", referrer: "http://case.local/user/login"
2016/12/16 15:18:13 [error] 963#963: *591 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
ReflectionException: Method yii\widgets\BaseListView::yii\widgets\{closure}() does not exist in /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php:199
Stack trace:
#0 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(199): ReflectionMethod->__construct('yii\\widgets\\Bas...', 'yii\\widgets\\{cl...')
#1 /var/www/case/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('yii\\widgets\\Bas...')
#2 /var/www/case/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/case/v...')
#3 /var/www/case/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/case/v...', Array)
#4 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('/var/www/case/v...', Array, Object(yii\web\ErrorHandler))
#5 /var/www/case/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 /var/www/case/vendor/yiisoft/yi" while reading response header from upstream, client: 127.0.0.1, server: case.local, request: "GET /operations/history/index?page=1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "case.local"
